/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import controller.Math;
/**
 *
 * @author behof
 */
public class Tela4 extends javax.swing.JPanel {

    /**
     * Creates new form Tela4
     */
    public Tela4() {
        initComponents();
        inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelResult = new javax.swing.JLabel();
        jTextFieldChar1 = new javax.swing.JTextField();
        jTextFieldChar2 = new javax.swing.JTextField();
        jButton = new javax.swing.JButton();

        jLabelResult.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelResult.setText("Resultado");

        jTextFieldChar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldChar2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton.setText("Dividir");
        jButton.addActionListener(this::jButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jTextFieldChar1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldChar2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton)
                            .addComponent(jLabelResult))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldChar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldChar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton)
                .addGap(18, 18, 18)
                .addComponent(jLabelResult)
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        c.dividir();
    }//GEN-LAST:event_jButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JTextField jTextFieldChar1;
    private javax.swing.JTextField jTextFieldChar2;
    // End of variables declaration//GEN-END:variables
    Math c;
    public void inicio(){
        c = new Math();
        c.jButton = jButton;
        c.jLabelResult = jLabelResult;
        c.jTextFieldChar1 = jTextFieldChar1;
        c.jTextFieldChar2 = jTextFieldChar2;
    }
}
